In [1]:
import pandas as pd

In [2]:
path="/content/drive/MyDrive/Datasets/Fake News Data/train.csv"


In [3]:
df=pd.read_csv(path)

In [4]:
df.head()

id  ... label
0   0  ...     1
1   1  ...     0
2   2  ...     1
3   3  ...     1
4   4  ...     1

[5 rows x 5 columns]

In [5]:
df=df.dropna()

In [6]:
X=df.drop("label",axis=1)

In [7]:
y=df["label"]

In [8]:
X.shape

(18285, 4)

In [9]:
y.shape

(18285,)

In [10]:
import tensorflow as tf

In [11]:
print(tf.__version__)

2.4.0


In [12]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [13]:

### Vocabulary size
voc_size=5000

In [14]:
messages=X.copy()

In [15]:

messages['title'][1]

'FLYNN: Hillary Clinton, Big Woman on Campus - Breitbart'

In [16]:
messages.reset_index(inplace=True)


In [17]:

import nltk
import re
from nltk.corpus import stopwords

In [18]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [19]:
### Dataset Preprocessing
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    print(i)
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

Streaming output truncated to the last 5000 lines.
13285
13286
13287
13288
13289
13290
13291
13292
13293
13294
13295
13296
13297
13298
13299
13300
13301
13302
13303
13304
13305
13306
13307
13308
13309
13310
13311
13312
13313
13314
13315
13316
13317
13318
13319
13320
13321
13322
13323
13324
13325
13326
13327
13328
13329
13330
13331
13332
13333
13334
13335
13336
13337
13338
13339
13340
13341
13342
13343
13344
13345
13346
13347
13348
13349
13350
13351
13352
13353
13354
13355
13356
13357
13358
13359
13360
13361
13362
13363
13364
13365
13366
13367
13368
13369
13370
13371
13372
13373
13374
13375
13376
13377
13378
13379
13380
13381
13382
13383
13384
13385
13386
13387
13388
13389
13390
13391
13392
13393
13394
13395
13396
13397
13398
13399
13400
13401
13402
13403
13404
13405
13406
13407
13408
13409
13410
13411
13412
13413
13414
13415
13416
13417
13418
13419
13420
13421
13422
13423
13424
13425
13426
13427
13428
13429
13430
13431
13432
13433
13434
13435
13436
13437
13438
13439
13440
13441
13442
1

In [20]:
#### Embedding Representation

In [22]:
onehot_repr=[one_hot(words,voc_size)for words in corpus ]

In [23]:
onehot_repr

[[2036, 1842, 4621, 2306, 1343, 124, 4142, 737, 2295, 1746],
 [1419, 2477, 2319, 2645, 3485, 1934, 1865],
 [4647, 1846, 716, 2730],
 [1083, 1169, 2290, 3478, 3965, 2849],
 [3761, 3485, 3929, 3703, 452, 38, 3485, 2150, 1615, 2068],
 [878,
  3024,
  1579,
  733,
  2164,
  2335,
  4276,
  3057,
  858,
  553,
  2794,
  568,
  1777,
  48,
  1865],
 [1562, 2017, 1803, 4819, 2960, 3152, 225, 4459, 482, 3315, 4041],
 [1822, 1332, 3127, 3902, 3407, 652, 2335, 1736, 482, 3315, 4041],
 [1050, 2375, 3240, 1425, 2177, 634, 1297, 2706, 2335, 842],
 [601, 4457, 3396, 2075, 261, 3197, 784, 4433],
 [4538, 3777, 4293, 2065, 238, 1080, 2465, 1649, 849, 1651, 39],
 [3478, 1784, 1343, 634, 2335, 3407],
 [1374, 791, 157, 392, 3994, 2711, 337, 2068, 3155],
 [2774, 4481, 2141, 1248, 1174, 4006, 4160, 482, 3315, 4041],
 [2438, 3432, 478, 221, 1475, 482, 3315, 4041],
 [1554, 2769, 974, 2664, 1018, 2763, 2407, 2608, 4908, 2747],
 [1762, 2404, 2477],
 [2933, 2477, 971, 3594, 2335, 4915, 446, 1865],
 [2575, 1874, 

In [24]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ...  737 2295 1746]
 [   0    0    0 ... 3485 1934 1865]
 [   0    0    0 ... 1846  716 2730]
 ...
 [   0    0    0 ...  482 3315 4041]
 [   0    0    0 ... 1699 1689 2810]
 [   0    0    0 ... 1070 2068 3332]]


In [25]:

embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0, 2036,
       1842, 4621, 2306, 1343,  124, 4142,  737, 2295, 1746], dtype=int32)

In [26]:

## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 20, 40)            200000    
_________________________________________________________________
lstm (LSTM)                  (None, 100)               56400     
_________________________________________________________________
dense (Dense)                (None, 1)                 101       
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [27]:
len(embedded_docs),y.shape

(18285, (18285,))

In [28]:

import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [29]:
X_final.shape,y_final.shape

((18285, 20), (18285,))

In [30]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

In [31]:
### Finally Training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=20,batch_size=64)

Epoch 1/20
192/192 [==============================] - 10s 10ms/step - loss: 0.4947 - accuracy: 0.7286 - val_loss: 0.1921 - val_accuracy: 0.9190
Epoch 2/20
192/192 [==============================] - 2s 8ms/step - loss: 0.1415 - accuracy: 0.9466 - val_loss: 0.1907 - val_accuracy: 0.9233
Epoch 3/20
192/192 [==============================] - 2s 8ms/step - loss: 0.0898 - accuracy: 0.9685 - val_loss: 0.2152 - val_accuracy: 0.9178
Epoch 4/20
192/192 [==============================] - 1s 8ms/step - loss: 0.0599 - accuracy: 0.9793 - val_loss: 0.2763 - val_accuracy: 0.9037
Epoch 5/20
192/192 [==============================] - 2s 8ms/step - loss: 0.0415 - accuracy: 0.9876 - val_loss: 0.2695 - val_accuracy: 0.9145
Epoch 6/20
192/192 [==============================] - 2s 8ms/step - loss: 0.0250 - accuracy: 0.9924 - val_loss: 0.3848 - val_accuracy: 0.9115
Epoch 7/20
192/192 [==============================] - 1s 8ms/step - loss: 0.0145 - accuracy: 0.9969 - val_loss: 0.4389 - val_accuracy: 0.9039
Epoc

In [32]:
y_pred=model.predict_classes(X_test)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [33]:

from sklearn.metrics import confusion_matrix

In [34]:
confusion_matrix(y_test,y_pred)

array([[3139,  280],
       [ 268, 2348]])

In [36]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9091963545981773