In [1]:
import pandas as pd

In [3]:
path="/content/drive/MyDrive/Datasets/Fake News Data/train.csv"


In [4]:
df=pd.read_csv(path)

In [5]:
df.head()

id  ... label
0   0  ...     1
1   1  ...     0
2   2  ...     1
3   3  ...     1
4   4  ...     1

[5 rows x 5 columns]

In [6]:
df=df.dropna()

In [7]:
X=df.drop("label",axis=1)

In [8]:
y=df["label"]

In [9]:
X.shape

(18285, 4)

In [11]:
y.shape

(18285,)

In [13]:
y.value_counts()

0    10361
1     7924
Name: label, dtype: int64

In [15]:
import tensorflow as tf

In [16]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Bidirectional
from tensorflow.keras.layers import Dropout

In [17]:

### Vocabulary size
voc_size=5000

In [18]:
### Onehot Representation
messages=X.copy()

In [19]:
messages['title'][1]

'FLYNN: Hillary Clinton, Big Woman on Campus - Breitbart'

In [20]:
messages.reset_index(inplace=True)

In [21]:
import nltk
import re
from nltk.corpus import stopwords

In [22]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [23]:

### Dataset Preprocessing
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    print(i)
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

Streaming output truncated to the last 5000 lines.
13285
13286
13287
13288
13289
13290
13291
13292
13293
13294
13295
13296
13297
13298
13299
13300
13301
13302
13303
13304
13305
13306
13307
13308
13309
13310
13311
13312
13313
13314
13315
13316
13317
13318
13319
13320
13321
13322
13323
13324
13325
13326
13327
13328
13329
13330
13331
13332
13333
13334
13335
13336
13337
13338
13339
13340
13341
13342
13343
13344
13345
13346
13347
13348
13349
13350
13351
13352
13353
13354
13355
13356
13357
13358
13359
13360
13361
13362
13363
13364
13365
13366
13367
13368
13369
13370
13371
13372
13373
13374
13375
13376
13377
13378
13379
13380
13381
13382
13383
13384
13385
13386
13387
13388
13389
13390
13391
13392
13393
13394
13395
13396
13397
13398
13399
13400
13401
13402
13403
13404
13405
13406
13407
13408
13409
13410
13411
13412
13413
13414
13415
13416
13417
13418
13419
13420
13421
13422
13423
13424
13425
13426
13427
13428
13429
13430
13431
13432
13433
13434
13435
13436
13437
13438
13439
13440
13441
13442
1

In [24]:
#### Embedding Representation
onehot_repr=[one_hot(words,voc_size)for words in corpus ]
onehot_repr

[[2593, 4734, 1848, 1925, 2644, 380, 3765, 514, 4812, 314],
 [3373, 4136, 3744, 2493, 1185, 4973, 1754],
 [322, 3862, 334, 4713],
 [4844, 3297, 2158, 2735, 1084, 117],
 [4865, 1185, 3149, 1516, 636, 2802, 1185, 907, 2906, 2001],
 [2430,
  3102,
  183,
  2766,
  2389,
  1901,
  2605,
  726,
  145,
  4470,
  1920,
  535,
  1576,
  1524,
  1754],
 [3838, 426, 595, 536, 2361, 1850, 4554, 2478, 1972, 1772, 2637],
 [1444, 1126, 3333, 2780, 4831, 663, 1901, 4813, 1972, 1772, 2637],
 [1501, 1481, 2209, 1313, 520, 3810, 1860, 3270, 1901, 804],
 [4880, 1797, 4859, 3050, 113, 1158, 1683, 2373],
 [4383, 2334, 89, 4545, 3440, 2801, 2471, 2640, 3382, 91, 1725],
 [2735, 478, 2644, 3810, 1901, 4831],
 [4401, 4574, 235, 348, 532, 365, 2201, 1188, 129],
 [4606, 3218, 1361, 4833, 3773, 588, 4914, 1972, 1772, 2637],
 [2447, 1785, 556, 3030, 971, 1972, 1772, 2637],
 [4464, 248, 983, 2122, 2447, 4730, 4151, 295, 722, 3462],
 [3183, 315, 4136],
 [1503, 2222, 4975, 459, 1901, 2770, 4019, 1754],
 [3785, 4411, 

In [25]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ...  514 4812  314]
 [   0    0    0 ... 1185 4973 1754]
 [   0    0    0 ... 3862  334 4713]
 ...
 [   0    0    0 ... 1972 1772 2637]
 [   0    0    0 ... 3459 4950 4480]
 [   0    0    0 ... 2578 4022 4353]]


In [26]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0, 2593,
       4734, 1848, 1925, 2644,  380, 3765,  514, 4812,  314], dtype=int32)

In [28]:
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Bidirectional(LSTM(100)))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 20, 40)            200000    
_________________________________________________________________
bidirectional (Bidirectional (None, 200)               112800    
_________________________________________________________________
dropout (Dropout)            (None, 200)               0         
_________________________________________________________________
dense (Dense)                (None, 1)                 201       
Total params: 313,001
Trainable params: 313,001
Non-trainable params: 0
_________________________________________________________________
None


In [29]:
len(embedded_docs),y.shape

(18285, (18285,))

In [30]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [31]:
X_final.shape,y_final.shape

((18285, 20), (18285,))

In [32]:

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

In [33]:
### Finally Training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=50,batch_size=64)

Epoch 1/50
192/192 [==============================] - 11s 13ms/step - loss: 0.4759 - accuracy: 0.7336 - val_loss: 0.2020 - val_accuracy: 0.9171
Epoch 2/50
192/192 [==============================] - 2s 10ms/step - loss: 0.1339 - accuracy: 0.9487 - val_loss: 0.1957 - val_accuracy: 0.9176
Epoch 3/50
192/192 [==============================] - 2s 11ms/step - loss: 0.0884 - accuracy: 0.9734 - val_loss: 0.2294 - val_accuracy: 0.9171
Epoch 4/50
192/192 [==============================] - 2s 11ms/step - loss: 0.0639 - accuracy: 0.9788 - val_loss: 0.2866 - val_accuracy: 0.9109
Epoch 5/50
192/192 [==============================] - 2s 11ms/step - loss: 0.0451 - accuracy: 0.9839 - val_loss: 0.3108 - val_accuracy: 0.9127
Epoch 6/50
192/192 [==============================] - 2s 11ms/step - loss: 0.0239 - accuracy: 0.9928 - val_loss: 0.4157 - val_accuracy: 0.9162
Epoch 7/50
192/192 [==============================] - 2s 10ms/step - loss: 0.0285 - accuracy: 0.9926 - val_loss: 0.4554 - val_accuracy: 0.911

In [35]:
y_pred=model.predict_classes(X_test)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [36]:

from sklearn.metrics import confusion_matrix

In [37]:

confusion_matrix(y_test,y_pred)

array([[3108,  311],
       [ 246, 2370]])

In [38]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.907705053852527

In [39]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.93      0.91      0.92      3419
           1       0.88      0.91      0.89      2616

    accuracy                           0.91      6035
   macro avg       0.91      0.91      0.91      6035
weighted avg       0.91      0.91      0.91      6035

